from litellm import completion
from config import LLM_MODEL

CLINICAL_DISCLAIMER = (
    "\n\n---\n"
    "⚠️ CLINICAL DISCLAIMER: This report is generated by an AI system and is intended "
    "for informational purposes only. It does not constitute medical advice, diagnosis, "
    "or treatment. All measurements and assessments should be reviewed by a qualified "
    "healthcare professional before any clinical decisions are made."
)


def _call_llm(messages: list) -> str:
    response = completion(
        model=LLM_MODEL,
        messages=messages,
        temperature=0.3,
        max_tokens=2000,
    )
    return response.choices[0].message.content


def generate_assessment_report(
    patient: dict, session: dict, norms: dict,
    z_scores: dict = None, trends: dict = None
) -> str:
    patient_info = (
        f"Patient: {patient['name']}, Age: {patient.get('age', 'N/A')}, "
        f"Gender: {patient.get('gender', 'N/A')}, "
        f"Height: {patient.get('height_cm', 'N/A')} cm, "
        f"Weight: {patient.get('weight_kg', 'N/A')} kg"
    )
    m = session.get("measurements", {}) or {}
    reba = m.get("reba", {})
    rula = m.get("rula", {})
    temporal = m.get("temporal", {})

    # Build structured clinical context
    reba_str = (
        f"REBA: score={reba.get('final_score')}, risk={reba.get('risk_level')}, "
        f"Table A={reba.get('score_a')}, Table B={reba.get('score_b')}"
        if reba else "REBA: not computed"
    )
    rula_str = (
        f"RULA: grand score={rula.get('grand_score')}, action level={rula.get('action_level')}, "
        f"description={rula.get('action_description', '')}"
        if rula else "RULA: not computed"
    )
    temporal_str = ""
    if temporal:
        sway = temporal.get("postural_sway_index")
        fatigue = temporal.get("fatigue_index")
        sym_trend = temporal.get("symmetry_trend")
        temporal_str = (
            f"\nTemporal Analysis (30-second window):\n"
            f"  Postural sway index: {sway}\n"
            f"  Fatigue index (trunk drift): {fatigue}\n"
            f"  Symmetry trend: {sym_trend}\n"
            f"  Trunk flexion stats: {temporal.get('trunk_flexion')}\n"
            f"  Neck flexion stats: {temporal.get('neck_flexion')}"
        )

    lsi_str = ""
    lsi_keys = [k for k in m if k.startswith("lsi_")]
    if lsi_keys:
        lsi_parts = [f"{k.replace('lsi_','').replace('_',' ')}: {m[k]:.1f}%" for k in lsi_keys if m.get(k) is not None]
        lsi_str = f"\nBilateral LSI: {', '.join(lsi_parts)}"

    zscore_summary = ""
    if z_scores:
        significant = {k: v for k, v in z_scores.items() if abs(v.get("z_score", 0)) > 1.5}
        if significant:
            parts = [f"{k}: z={v['z_score']}, p={v['percentile']}th pct" for k, v in list(significant.items())[:6]]
            zscore_summary = f"\nSignificant z-scores (|z|>1.5): {'; '.join(parts)}"

    trend_summary = ""
    if trends:
        sig_trends = {k: v for k, v in trends.items() if v.get("significant") and k in (
            "symmetry_score", "posture_angle_deg", "reba_final_score", "trunk_flexion"
        )}
        if sig_trends:
            parts = [f"{k}: {v['trend']} (p={v['p_value']})" for k, v in sig_trends.items()]
            trend_summary = f"\nStatistically significant longitudinal trends: {'; '.join(parts)}"

    messages = [
        {
            "role": "system",
            "content": (
                "You are a clinical assessment AI for physical therapy and occupational health. "
                "Generate a structured, evidence-based clinical report using REBA/RULA ergonomic scores, "
                "anthropometric z-scores, bilateral symmetry indices, temporal postural analysis, and "
                "longitudinal trend data. Be concise, objective, and clinically precise."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Generate a clinical body assessment report:\n\n"
                f"## Patient\n{patient_info}\n\n"
                f"## Ergonomic Risk Scores\n{reba_str}\n{rula_str}\n\n"
                f"## Key Measurements\n"
                f"  Symmetry score: {m.get('symmetry_score')}%, "
                f"Ape index: {m.get('ape_index')}, "
                f"Cormic index: {m.get('cormic_index')}, "
                f"Shoulder-hip ratio: {m.get('shoulder_hip_ratio')}, "
                f"Depth confidence: {m.get('depth_confidence')}"
                f"{lsi_str}"
                f"{temporal_str}"
                f"{zscore_summary}"
                f"{trend_summary}\n\n"
                f"## Posture Alerts\n{session.get('posture_alerts', [])}\n\n"
                f"## Norm Comparison\n{norms}\n\n"
                "Structure your report as: 1) Executive Summary, 2) Postural Analysis, "
                "3) Ergonomic Risk Assessment, 4) Anthropometric Profile, "
                "5) Temporal Findings (if available), 6) Clinical Recommendations."
            ),
        },
    ]
    content = _call_llm(messages)
    return content + CLINICAL_DISCLAIMER


def generate_progress_report(patient: dict, current: dict, previous: dict, delta: dict) -> str:
    messages = [
        {
            "role": "system",
            "content": (
                "You are a clinical progress tracking AI for physical therapy. "
                "Analyze measurement changes between sessions and provide clinical insights."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Generate a progress report for patient: {patient['name']}\n\n"
                f"Current session measurements: {current.get('measurements', {})}\n\n"
                f"Previous session measurements: {previous.get('measurements', {})}\n\n"
                f"Changes: {delta}\n\n"
                "Summarize the patient's progress, improvements, and areas still needing attention."
            ),
        },
    ]
    content = _call_llm(messages)
    return content + CLINICAL_DISCLAIMER


def generate_soap_note(patient: dict, session: dict) -> str:
    m = session.get("measurements", {}) or {}
    reba = m.get("reba", {})
    temporal = m.get("temporal", {})
    temporal_note = ""
    if temporal:
        fatigue = temporal.get("fatigue_index")
        sway = temporal.get("postural_sway_index")
        if fatigue is not None or sway is not None:
            temporal_note = f"\nTemporal: fatigue_index={fatigue}, sway_index={sway}"

    messages = [
        {
            "role": "system",
            "content": (
                "You are a clinical documentation AI. Generate SOAP notes based on "
                "body measurement data including REBA/RULA ergonomic scores and temporal postural analysis. "
                "Format strictly as: Subjective, Objective, Assessment, Plan."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Generate a SOAP note for:\n"
                f"Patient: {patient['name']}, Age: {patient.get('age')}, Gender: {patient.get('gender')}\n"
                f"REBA score: {reba.get('final_score')} ({reba.get('risk_level')})\n"
                f"Symmetry: {m.get('symmetry_score')}%, Posture angle: {m.get('posture_angle_deg')}°\n"
                f"LSI arm: {m.get('lsi_arm')}%, LSI thigh: {m.get('lsi_thigh')}%"
                f"{temporal_note}\n"
                f"Posture Alerts: {session.get('posture_alerts', [])}\n"
                f"Session notes: {session.get('notes', 'None')}"
            ),
        },
    ]
    content = _call_llm(messages)
    return content + CLINICAL_DISCLAIMER


def chat_with_context(patient: dict, sessions: list, messages: list) -> str:
    session_summary = "\n".join([
        f"Session {i+1} ({s.get('session_date', 'N/A')}): {s.get('measurements', {})}"
        for i, s in enumerate(sessions[:5])
    ])

    system_prompt = (
        f"You are a clinical AI assistant helping a healthcare professional understand "
        f"patient data for {patient['name']} "
        f"(Age: {patient.get('age')}, Gender: {patient.get('gender')}).\n\n"
        f"Recent session data:\n{session_summary}\n\n"
        "Answer questions about this patient's measurements, posture, and progress. "
        "Always remind the user that clinical decisions should be made by qualified professionals."
    )

    llm_messages = [{"role": "system", "content": system_prompt}]
    for msg in messages[-20:]:
        llm_messages.append({"role": msg["role"], "content": msg["content"]})

    return _call_llm(llm_messages)
