from litellm import completion
from config import LLM_MODEL

CLINICAL_DISCLAIMER = (
    "\n\n---\n"
    "⚠️ CLINICAL DISCLAIMER: This report is generated by an AI system and is intended "
    "for informational purposes only. It does not constitute medical advice, diagnosis, "
    "or treatment. All measurements and assessments should be reviewed by a qualified "
    "healthcare professional before any clinical decisions are made."
)


def _call_llm(messages: list) -> str:
    response = completion(
        model=LLM_MODEL,
        messages=messages,
        temperature=0.3,
        max_tokens=2000,
    )
    return response.choices[0].message.content


def generate_assessment_report(patient: dict, session: dict, norms: dict) -> str:
    patient_info = (
        f"Patient: {patient['name']}, Age: {patient.get('age', 'N/A')}, "
        f"Gender: {patient.get('gender', 'N/A')}, "
        f"Height: {patient.get('height_cm', 'N/A')} cm, "
        f"Weight: {patient.get('weight_kg', 'N/A')} kg"
    )
    measurements_str = str(session.get("measurements", {}))
    alerts_str = str(session.get("posture_alerts", []))
    norms_str = str(norms)

    messages = [
        {
            "role": "system",
            "content": (
                "You are a clinical assessment AI assistant for physical therapy and orthopedic care. "
                "Generate professional clinical assessment reports based on body measurement data. "
                "Be concise, objective, and clinically relevant."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Generate a clinical body assessment report for the following patient:\n\n"
                f"{patient_info}\n\n"
                f"Measurements: {measurements_str}\n\n"
                f"Posture Alerts: {alerts_str}\n\n"
                f"Comparison to norms: {norms_str}\n\n"
                "Include: summary of findings, postural analysis, areas of concern, "
                "and recommendations for further evaluation."
            ),
        },
    ]
    content = _call_llm(messages)
    return content + CLINICAL_DISCLAIMER


def generate_progress_report(patient: dict, current: dict, previous: dict, delta: dict) -> str:
    messages = [
        {
            "role": "system",
            "content": (
                "You are a clinical progress tracking AI for physical therapy. "
                "Analyze measurement changes between sessions and provide clinical insights."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Generate a progress report for patient: {patient['name']}\n\n"
                f"Current session measurements: {current.get('measurements', {})}\n\n"
                f"Previous session measurements: {previous.get('measurements', {})}\n\n"
                f"Changes: {delta}\n\n"
                "Summarize the patient's progress, improvements, and areas still needing attention."
            ),
        },
    ]
    content = _call_llm(messages)
    return content + CLINICAL_DISCLAIMER


def generate_soap_note(patient: dict, session: dict) -> str:
    messages = [
        {
            "role": "system",
            "content": (
                "You are a clinical documentation AI. Generate SOAP notes based on "
                "body measurement data. Format strictly as: Subjective, Objective, Assessment, Plan."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Generate a SOAP note for:\n"
                f"Patient: {patient['name']}, Age: {patient.get('age')}, Gender: {patient.get('gender')}\n"
                f"Measurements: {session.get('measurements', {})}\n"
                f"Posture Alerts: {session.get('posture_alerts', [])}\n"
                f"Session notes: {session.get('notes', 'None')}"
            ),
        },
    ]
    content = _call_llm(messages)
    return content + CLINICAL_DISCLAIMER


def chat_with_context(patient: dict, sessions: list, messages: list) -> str:
    session_summary = "\n".join([
        f"Session {i+1} ({s.get('session_date', 'N/A')}): {s.get('measurements', {})}"
        for i, s in enumerate(sessions[:5])
    ])

    system_prompt = (
        f"You are a clinical AI assistant helping a healthcare professional understand "
        f"patient data for {patient['name']} "
        f"(Age: {patient.get('age')}, Gender: {patient.get('gender')}).\n\n"
        f"Recent session data:\n{session_summary}\n\n"
        "Answer questions about this patient's measurements, posture, and progress. "
        "Always remind the user that clinical decisions should be made by qualified professionals."
    )

    llm_messages = [{"role": "system", "content": system_prompt}]
    for msg in messages[-20:]:
        llm_messages.append({"role": msg["role"], "content": msg["content"]})

    return _call_llm(llm_messages)
